debug: false
data_dir: "/home/pervinco/Datasets/leash-bio"
save_dir: "./runs"
ckpt_dir: "/home/pervinco/DL-basic/GNN/runs/2024-06-13-15-28-00"

train_parquet: "/home/pervinco/Datasets/leash-bio/train.parquet"
test_parquet: "/home/pervinco/Datasets/leash-bio/test.parquet"

num_train_data: 500000
num_valid_data: 50000
num_workers: 4

epochs: 1000
batch_size: 64
learning_rate: 0.0001

num_layers: 8
num_heads: 4
hidden_dim: 64
drop_prob: 0.2
early_stop_patience: 10

predict_top_k: 5
feature_top_n: 20
chunk_size: 1000000

target_proteins:
  - HSA
  - sEH
  - BRD4

uniprot_dicts:
  sEH: "P34913"
  BRD4: "O60885"
  HSA: "P02768"
