debug: false
data_dir: "/home/pervinco/Datasets/leash-bio"
save_dir: "./runs"
ckpt_dir: "/home/pervinco/DL-basic/GNN/runs/2024-06-13-15-28-00"

train_parquet: "/home/pervinco/Datasets/leash-bio/train.parquet"
test_parquet: "/home/pervinco/Datasets/leash-bio/test.parquet"

num_train_data: 100000 ## 1589906, 146828462
num_valid_data: 50000
num_workers: 8

model: "GCN"
epochs: 1000
batch_size: 128
learning_rate: 0.0001
weight_decay: 0.000002

min_lr: 0.0000001
max_lr: 0.0001
T_0: 200
T_mult: 2

num_layers: 4
num_heads: 4
hidden_dim: 128
drop_prob: 0.2
early_stop_patience: 10

num_node_features: 69 ## 29, 30
num_edge_features: 6 ## 6
protein_dim: 150
protein_embedding_dim: 1024

predict_top_k: 5
feature_top_n: 20
chunk_size: 1000000

target_proteins:
  - HSA
  - sEH
  - BRD4

uniprot_dicts:
  sEH: "P34913"
  BRD4: "O60885"
  HSA: "P02768"
