paths:
  save_dir: "./runs"
  data_dir: "/home/pervinco/Datasets"

lang:
  src: "de"
  trg: "en"

hyps:
  epochs: 100
  batch_size: 128
  learning_rate: 0.0001
  grad_clip: 10.0
  max_length: 50

model:
  embed_dim: 256
  encoder_hidden_dim: 512
  decoder_hidden_dim: 512
  encoder_drop_prob: 0.5
  decoder_drop_prob: 0.5

tokens:
  unk_token: 0
  pad_token: 1
  sos_token: 1
  eos_token: 2
