paths:
  save_dir: "./runs"
  data_dir: "/home/pervinco/Datasets"

lang:
  src: "de"
  trg: "en"
  n_rows: 50000

training:
  epochs: 100
  batch_size: 64
  learning_rate: 0.007
  grad_clip: 1
  max_length: 10

model:
  embed_dim: 620
  hidden_dim: 1000
  encoder_layers: 3
  decoder_layers: 2
  encoder_dropout: 0.2
  decoder_dropout: 0.2

tokens:
  unk_token: 0
  pad_token: 1
  sos_token: 2
  eos_token: 3
